/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED4.h"
#include "LED4_aliases.h"
#include "LED3.h"
#include "LED3_aliases.h"
#include "LED2.h"
#include "LED2_aliases.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "LED0.h"
#include "LED0_aliases.h"
#include "UART_DBG.h"
#include "UART_DBG_SPI_UART.h"
#include "UART_DBG_PINS.h"
#include "UART_DBG_SPI_UART_PVT.h"
#include "UART_DBG_PVT.h"
#include "UART_DBG_BOOT.h"
#include "LED5.h"
#include "LED5_aliases.h"
#include "UART_GPS.h"
#include "UART_GPS_SPI_UART.h"
#include "UART_GPS_PINS.h"
#include "UART_GPS_SPI_UART_PVT.h"
#include "UART_GPS_PVT.h"
#include "UART_GPS_BOOT.h"
#include "LED6.h"
#include "LED6_aliases.h"
#include "WDT_ISR.h"
#include "UART_FC.h"
#include "UART_FC_SPI_UART.h"
#include "UART_FC_PINS.h"
#include "UART_FC_SPI_UART_PVT.h"
#include "UART_FC_PVT.h"
#include "UART_FC_BOOT.h"
#include "UART_DBG_SCBCLK.h"
#include "UART_DBG_tx.h"
#include "UART_DBG_tx_aliases.h"
#include "UART_DBG_SCB_IRQ.h"
#include "UART_DBG_rx.h"
#include "UART_DBG_rx_aliases.h"
#include "UART_GPS_SCBCLK.h"
#include "UART_GPS_tx.h"
#include "UART_GPS_tx_aliases.h"
#include "UART_GPS_SCB_IRQ.h"
#include "UART_GPS_rx.h"
#include "UART_GPS_rx_aliases.h"
#include "UART_FC_SCBCLK.h"
#include "UART_FC_tx.h"
#include "UART_FC_tx_aliases.h"
#include "UART_FC_SCB_IRQ.h"
#include "UART_FC_rx.h"
#include "UART_FC_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

